#!/bin/bash

function logTrace {
  echo -e "\e[90m$1\e[0m"
}

function logInfo {
  echo -e "\e[96m$1\e[0m"
}

function logOk {
  echo -e "\e[92m$1\e[0m"
}

function logWarn {
  echo -e "\e[93m$1\e[0m"
}

function logError {
  echo -e "\e[1;91m$1\e[0m"
}

function logFatal {
  echo -e "\e[1;101m$1\e[0m"
}


