#!/bin/bash

# manage an application shortcut



#** create a *.desktop file in the user application list
#* $1 : application name, will generate "$1.desktop"
#* $2 : exec path
#* $3 : icon path
#* $4 : short description (optionnal)
#* $5 : categories (optionnal)
function createDesktopFile {
  if [ $# -lt 3 ]; then
    echo "usage : createDesktopFile APPLICATION_NAME EXEC_PATH ICON_PATH [SHORT_DESCRIPTION] [CATEGORIES]"
    return 1
  fi
  TARGET_FILE="$HOME/.local/share/applications/$1.desktop"
  
  if [ ! -e "$TARGET_FILE" ]; then
    logInfo "Creating desktop file : $TARGET_FILE ..."

    echo "[Desktop Entry]
Version=1.0
Name=$1
Exec=$PATH_INSTALL/eclipse
Icon=$PATH_INSTALL/icon.xpm
Type=Application
Terminal=false
StartupNotify=true
" > "$TARGET_FILE"

    if [ $# -ge 4 ]; then
      echo "Comment=$4" >> "$TARGET_FILE"
    fi

    if [ $# -ge 5 ]; then
      echo "Categories=$5" >> "$TARGET_FILE"
    fi

  fi

  if [ ! -x "$TARGET_FILE" ]; then 
    chmod u+x "$TARGET_FILE"
  fi

}


#** Register an existing *.desktop file in the Ubuntu launcher.
#* $1 : application name, the desktop file is "$1.desktop"
function addInLauncher {
  if [ $# -lt 1 ]; then
    echo "usage : addInLauncher APPLICATION_NAME"
    echo "  APPLICATION_NAME the name of the desktop file will be 'APPLICATION_NAME.desktop'"
    return 1
  fi

  LAUNCHER_FILE="$1.desktop"
  LAUNCHER_LIST=`gsettings get com.canonical.Unity.Launcher favorites`

  LAUNCHER_GREP=`echo "$LAUNCHER_LIST" | grep -o "$LAUNCHER_FILE" | wc -c`

  if [ 0 -lt "$LAUNCHER_GREP" ]; then
    logTrace "Already in launcher."
  else
    logInfo "Install '$1' in launcher..."
    logTrace "before : $LAUNCHER_LIST"
    LAUNCHER_LIST_NEW=`echo $LAUNCHER_LIST | sed -e "s@]@, 'application://${LAUNCHER_FILE}']@"`
    logTrace "after : $LAUNCHER_LIST_NEW"
    gsettings set com.canonical.Unity.Launcher favorites "$LAUNCHER_LIST_NEW"
  fi
}

